### PR TITLE
Virt UUID spec

### PR DESCRIPTION
**Pull request by TripleJQK**

### CODE REVIEW

**Comment by eduardocerqueira** [comment]
we are investigating the error happened during the tests, more coming soon.

**Comment by eduardocerqueira** [comment]
test this please

**Comment by eduardocerqueira** [comment]
There is one failure only for rhel-7.5 during systemd scheduler tests. I don't believe it is related to the changes on this PR, so if you need to merge this, go ahead, otherwise I will re-run this test later. We are debugging that test to identify the root cause.

**Comment by eduardocerqueira** [comment]
test this please

**Comment by TripleJQK** [comment]
close as nonrelated commit include

**Pull request closed without merging**
