### PR TITLE
Update spec for lvs_noheadings with seg_monitor

### PR DESCRIPTION
**Pull request by JoySnow**

### CODE REVIEW

**Comment by JoySnow** [comment]
Refer to https://github.com/RedHatInsights/insights-frontend-assets/pull/144 ,
no adding for  lvs_noheadings_all.

**Comment by SteveHNH** [comment]
@JoySnow Can you actually open this one against the `insights-core-assets` repo? We no longer use this one for uploader.json updates.

**Comment by JoySnow** [comment]
@SteveHNH  Thanks for your reminding. I remake a PR https://github.com/RedHatInsights/insights-core-assets/pull/31

**Comment by JoySnow** [comment]
A proper replacement is at https://github.com/RedHatInsights/insights-core-assets/pull/31 .
Close this PR.

**Pull request closed without merging**
