### PR TITLE
New spec to collect docker container inspect

### PR DESCRIPTION
**Pull request by wushiqinlou**

### CODE REVIEW

**Comment by eduardocerqueira** [comment]
Error was due network connectivity "stderr: fatal: unable to access 'https://github.com/RedHatInsights/insights-tests.git/" we are looking into this now and we will ask to re-test this PR

**Comment by eduardocerqueira** [comment]
test this please

**Comment by wushiqinlou** [comment]
test this please

**Comment by bfahr** [comment]
@wushiqinlou please resubmit this PR against the `uploader_json` branch.

**Comment by bfahr** [comment]
Also please submit this PR against the `uploader_json` branch.

**Comment by wushiqinlou** [comment]
@bfahr - This command depends on the pre_command. No other way to get this information. I will close this PR if we have no method to fix this issue currently.

**Pull request closed without merging**
