### PR TITLE
L3 agent log

### PR DESCRIPTION
**Pull request by chenlizhong**

### CODE REVIEW

**Comment by eduardocerqueira** [comment]
1 test failed, I am investigating

**Comment by eduardocerqueira** [comment]
test this please

**Comment by xiangce** [comment]
@chenlizhong - There are some conflicts, I think you need to rebase your local branch `l3_agent_log` with the latest `uploader_json` branch again.

**Comment by eduardocerqueira** [comment]
There is one failure only for rhel-7.5 during systemd scheduler tests. I don't believe it is related to the changes on this PR, so if you need to merge this, go ahead, otherwise I will re-run this test later. We are debugging that test to identify the root cause.

**Comment by eduardocerqueira** [comment]
test this please

**Comment by eduardocerqueira** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Pull request merged**
