### PR TITLE
uploader: Add rhv-log-collector-analyzer

### PR DESCRIPTION
**Pull request by dougsland**

### CODE REVIEW

**Comment by bfahr** [comment]
This PR needs to be closed, based on discussions with @dougsland.

**Comment by dougsland** [comment]
@bfahr closed? Unfortunately I don't follow Bob.

**Comment by bfahr** [comment]
@dougsland my understanding was originally that we were not going to merge this.  However, based on some of the recent email maybe I don't have all of the information to make that decision.  I'm going to reopen the Jira, and leave this PR open.

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by sandrobonazzola** [comment]
Where can I see result of the test? (assuming "test this please" is triggering some automated test in jenkins)

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
Yep, e.g. https://github.com/RedHatInsights/insights-frontend-assets/pull/151 we've got automated test, but we're checking why "test this please" didn't run it for PR#105

**Comment by eduardocerqueira** [comment]
test this please

**Comment by eduardocerqueira** [comment]
test this please

**Comment by dougsland** [comment]
The failure doesn't seems related to the patch, please let me know if I need to something in my side.

Setting status of 867caf708c106ceeb760e9baa49d999e168b8e0e to FAILURE with url http://10.8.252.209:8080/job/CI-PR-insights-frontend-assets/125/ and message: 'Build finished. '
java.io.FileNotFoundException
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:167)
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:159)
	at jenkins.plugins.git.GitSCMFileSystem$3.invoke(GitSCMFileSystem.java:193)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
	at jenkins.plugins.git.GitSCMFileSystem.invoke(GitSCMFileSystem.java:189)
	at jenkins.plugins.git.GitSCMFile.content(GitSCMFile.java:159)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:338)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:110)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:302)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

**Comment by eduardocerqueira** [comment]
Hi @dougsland  you are right! the error is not related to your patch. it is some configuration in our Jenkins and we are investigating.

**Comment by eduardocerqueira** [comment]
test this please

**Comment by eduardocerqueira** [comment]
test this please

**Comment by eduardocerqueira** [comment]
@YakovLittle fixed Jenkins trigger integration with this PR. Now you can ask Jenkins to re-test this PR many times as needed. @dougsland just a follow up, there is another internal issue and QE is looking into.

**Comment by eduardocerqueira** [comment]
test this please

**Comment by dougsland** [comment]
Hi everyone, any additional step here? Can we move forward?

**Comment by doron-fediuck** [comment]
@eduardocerqueira is there anything else needed or can it be merged?
Who can merge this?

**Comment by eduardocerqueira** [comment]
Hi @doron-fediuck, sorry for delay. I can only speak about the CI and tests for this PR. @bfahr could you help here?

**Comment by dougsland** [comment]
Looks like a new error appeared in the build but I don't have access to check the error message. @bfahr  any guidance? Thanks!

**Comment by miclark** [comment]
I would like to close this PR without merging, revisiting after some discussions with the RHEV team on different data collection approaches.

The collection here is a bit out of alignment with respect to Red Hat Insights data collection.  It moves the rule logic onto the client instead of on the server.  This means that updated (new, corrected, or removed checks) can only be updated via an rpm release instead of a server-side change.

Discussions with the RHEV engineering team to make adjustments to better align are being scheduled.

**Comment by bfahr** [comment]
@dougsland we will go ahead and close this PR.  You can submit any new PRs against the [insights-core-assets](https://github.com/RedHatInsights/insights-core-assets) project, `uploader_json` branch.

**Comment by dankenigsberg** [comment]
@miclark We intentionally chose this mechanism in order to avoid a tight coupling between the Insights server and RHV. Our warning queries are using non-API access to the RHV database. No application besides RHV itself should do that. If you ship these queries within Insights, they are likely to break in a near-future RHV update.

Please reconsider this approach. I believe that we should use an agreed-upon json API between RHV and Insights.

**Pull request closed without merging**
