### PR TITLE
add delete filter to lsof

### PR DESCRIPTION
**Pull request by TripleJQK**

### CODE REVIEW

**Comment by TripleJQK** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by bfahr** [comment]
@TripleJQK this PR is not necessary.  Filters are added in the production release process based on the filters included in parsers and rules.

**Pull request closed without merging**
