### PR TITLE
Add new filter to ps_auxww to collect greenplum and postgres processes

### PR DESCRIPTION
**Pull request by lonicerae**

### CODE REVIEW

**Comment by xiangce** [comment]
Hi @lonicerae , please change the base branch and the merge target to `uploader_json`.

**Comment by eduardocerqueira** [comment]
we are investigating the error happened during the tests, more coming soon.

**Comment by eduardocerqueira** [comment]
we are investigating the error happened during the tests, more coming soon.

**Comment by eduardocerqueira** [comment]
test this please

**Pull request merged**
