### PR TITLE
New spec collect init_process_group

### PR DESCRIPTION
**Pull request by wushiqinlou**

### CODE REVIEW

**Comment by bfahr** [comment]
@wushiqinlou his PR looks good, but needs to be resubmitted against the `uploader_json` branch.

**Comment by wushiqinlou** [comment]
@bfahr - I resolve the conflict, please have a check.

**Comment by eduardocerqueira** [comment]
test this please

**Comment by wushiqinlou** [comment]
@bfahr - sorry for misunderstanding your request, I changed the merge branch, please have a check.

**Comment by bfahr** [comment]
@wushiqinlou your PR has several changes that are present because your PR was generated from the master branch.  The simplest way to fix this PR is to create a new PR that is from your fork of the `uploader_json` branch.  Then the PR will have only the changes required for your new spec.

**Comment by wushiqinlou** [comment]
@bfahr - Got it, I will close it and submit a new PR. https://github.com/RedHatInsights/insights-frontend-assets/pull/140/

**Pull request closed without merging**
