### PR TITLE
Add spec for odbc.ini and idbcinst.ini

### PR DESCRIPTION
**Pull request by JoySnow**
Signed-off-by: XiaoXue Wang <xiaoxwan@redhat.com>

### CODE REVIEW

**Comment by eduardocerqueira** [comment]
There is one failure only for rhel-7.5 during systemd scheduler tests. I don't believe it is related to the changes on this PR, so if you need to merge this, go ahead, otherwise I will re-run this test later. We are debugging that test to identify the root cause.

**Comment by eduardocerqueira** [comment]
test this please

**Comment by YakovLittle** [comment]
We've got the GIT issue: 
> git fetch --tags --progress https://github.com/RedHatInsights/insights-tests.git +refs/heads/*:refs/remotes/origin/*
ERROR: Timeout after 10 minutes
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/RedHatInsights/insights-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:

**Comment by YakovLittle** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Pull request merged**
