### PR TITLE
spec for ls osroot(ls /)

### PR DESCRIPTION
**Pull request by TripleJQK**

### CODE REVIEW

**Comment by xiangce** [comment]
I did a test with the `uploader_json`, I don't think the newly added `ls_osroot` works for the `LsOsroot` parser.

Here is my test log:

~~~
# ls insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-l*
insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-la_.dev.null_.var.www  insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-lanR_.sys.firmware
insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-lan                    insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-lanR_.var.lib.docker.volumes
insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-lanR_.boot             insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-la_.var.log_.var.log.audit
insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-lanR_.dev              insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-l_.boot.grub2.grub.cfg
insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-lanR_.dev.disk         insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-l_.boot.grub.grub.conf
insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-lanR_.etc              insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-l_.etc.ssh.sshd_config

# python -m insights -p insights.parsers.ls_osroot -- /tmp/a.tar.gz
INFO:insights.core.dr:Trying insights.specs.default.DefaultSpecs.ls_osroot
INFO:insights.core.dr:Trying insights.specs.insights_archive.InsightsArchiveSpecs.ls_osroot
INFO:insights.core.dr:Trying insights.specs.Specs.ls_osroot
INFO:insights.core.dr:Trying insights.parsers.ls_osroot.LsOsroot


datasource instances:

parser instances:

# python -m insights -p insights.parsers.ls_dev -- /tmp/a.tar.gz                                                                                                                             
INFO:insights.core.dr:Trying insights.specs.insights_archive.InsightsArchiveSpecs.ls_dev
INFO:insights.core.dr:Trying insights.specs.default.DefaultSpecs.ls_dev
INFO:insights.core.dr:Trying insights.specs.Specs.ls_dev
INFO:insights.core.dr:Trying insights.parsers.ls_dev.LsDev


datasource instances:
'insights.specs.Specs.ls_dev:'
TextFileProvider("/tmp/tmpi713HH/insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-lanR_.dev")                                                                             

'insights.specs.insights_archive.InsightsArchiveSpecs.ls_dev:'
TextFileProvider("/tmp/tmpi713HH/insights-liuxc-rhel-client-test-20180606015748/insights_commands/ls_-lanR_.dev")                                                                             


parser instances:
'insights.parsers.ls_dev.LsDev:'
<insights.parsers.ls_dev.LsDev object at 0x7fe8f08bf0d0>
~~~

I think this might be caused by https://github.com/RedHatInsights/insights-frontend-assets/issues/28#issuecomment-387285237, the insights-core could not map the `insights_commands/ls_-lan` in the collected data with the `ls_osroot` spec.

**Comment by csams** [comment]
@xiangce Try changing the spec in `insights/specs/insights_archive.py` to `ls_osroot = simple_file("insights_commands/ls_-lan")`

**Comment by xiangce** [comment]
@csams - It's OK to change the `simple_file` and truncate the last `.`, but as I mentioned in https://github.com/RedHatInsights/insights-frontend-assets/issues/28#issuecomment-387285237, the current FileListing Class cannot parser the `simple_file` that doesn't contain any `.` correctly, See https://github.com/RedHatInsights/insights-core/blob/b3b7ceb9d1e691ad27dcc3b94bd74f1e7950af8a/insights/core/__init__.py#L1171,

I'll open an issue for it to the insights-core project.

**Comment by xiangce** [comment]
Issue opened: https://github.com/RedHatInsights/insights-core/issues/1203

**Pull request merged**
