### PR TITLE
new filter for messages

### PR DESCRIPTION
**Pull request by TripleJQK**
https://github.com/RedHatInsights/insights-plugins/pull/843

### CODE REVIEW

**Comment by TripleJQK** [comment]
https://projects.engineering.redhat.com/browse/INSPEC-16

**Comment by eduardocerqueira** [comment]
I am looking into the tests that fail to see if it something related to the change or some fail at my end. I will add a comment here very soon.

**Comment by eduardocerqueira** [comment]
quick update about the fail for Jenkins regression tests, it is NOT related to the change in any file(s) for this PR, the password for insights-qa account was changed and it is breaking one of tests. I will re-run the job!

**Comment by eduardocerqueira** [comment]
test this please

**Comment by YakovLittle** [comment]
test this please

**Comment by xiangce** [comment]
Added, see 40681a4d

**Pull request closed without merging**
